### ISSUE TITLE
Add Deputy Project Leader role to Bylaws properly

### ISSUE THREAD

**Issue by pmai** [modelica/MA-Bylaws#10]
Current practice is to have deputy project leaders be part of the MA Board; however the bylaws do not mention this, nor do they e.g. require deputy project leaders to even be MA members (only project leaders need to be).

While adding this, the voting procedure in the board w.r.t. deputies should also be clarified (e.g. deputies only vote if the proper PL is not present).

As discussed also in today's MA board meeting on 2022-05-25

**Comment by GallLeo** [comment]
Agreed. 
As identified in yesterday's Annual Meeting: 
It would be good to clarify, whether Deputy Project leaders have to be MA member 
(my personal impression: yes, personal membership or organizational representative would be required).

**Comment by chrbertsch** [comment]
Pierre: For the MA board members: organazial or personal members.
Pierre, Hans, Christian: require MA Project leaders and deputies to fulfill requirements of MA board members.
