### ISSUE TITLE
Make Annual Assembly Meeting more flexible

### ISSUE THREAD

**Issue by MartinOtter** [modelica/MA-Bylaws#11]
Topics proposed at the MA board meeting on May 25, 2022:

- Annual Assembly Meeting should be Online by default.
   MA currently relies on a temporary law in Sweden to have remote annual meetings (due to COVID, valid for 2022). Probably will be extended or become permanent. Better, to define this in the Bylaws.
- It should be possible to define the agenda  more flexibly (only legally required parts should be stated in the agenda).
- Annual Assembly Meeting can take place until end of June, instead end of May.
- Add recommendation to prepare the annual assembly meeting at least 2 weeks beforehand within a MA board meeting.

**Comment by GallLeo** [comment]
We could check if we can vote after the meeting via standard electronic voting (one week)?
This would simplify the organization of votings and all members would be able to vote.
But, this has to be compliant with Swedish law.

**Comment by chrbertsch** [comment]
> We could check if we can vote after the meeting via standard electronic voting (one week)? This would simplify the organization of votings and all members would be able to vote. But, this has to be compliant with Swedish law.

Francesco, Hans: We have digital meetings with realtime electronic meetings, and "electronic votings". We have to do it either way.

All other points are addressed in other issues.
