### ISSUE TITLE
Remove requirement for two assembly meetings per year

### ISSUE THREAD

**Issue by chrbertsch** [modelica/MA-Bylaws#18]
... if not required by Swedish law

**Comment by HansOlsson** [comment]
It's not for an economic association as far as I can see.

However, it is required for a "housing cooperative" (BRF in Swedish - a common housing form in Sweden); unless _everyone_ is in favor; and I would assume many are familiar with that.

**Comment by chrbertsch** [comment]
Discussion Pierre, Hans, Francesco, Christian: OK to remove it
Hans: my comment was w.r.t. to two meetings to change the bylaws.
