### ISSUE TITLE
Remove clause about what a typical contribution to MA projects or other parts of MA is

### ISSUE THREAD

**Issue by casella** [modelica/MA-Bylaws#21]
In Section 3 it is stated that
> For an individual person to become a member of the Modelica Association, the person must have contributed to an MA Project (see § 21 - § 23) or to other parts of the Modelica Association. 

Then it is stated that

> A contribution is typically demonstrated by
>>(a) participating in two previous project meetings of registered MA Projects during the previous twelve-month period, or
>(b) participating in two previous Assembly meetings (see § 12) during the previous twelve-month period.

In the past, participating to a physical meeting meant some commitment, but now we have digital meetings, so these two points are worthless, per se. 

Proposal:  remove the exemplification clauses. The deciding body will determine if the person actually contributed in some meaningful way.

Christian, Francesco, Hans, Pierre: OK

**Comment by chrbertsch** [comment]
Covered by the commit fixing #22
