### ISSUE TITLE
Digital assemblies only

### ISSUE THREAD

**Issue by casella** [modelica/MA-Bylaws#23]
Section 5 currently states: 
> MA's highest decision-making body is the Assembly which consists of all MA members (individual persons and liaison members/representatives of member organizations) that are present at an Assembly meeting or take place in an electronic vote.
> 
> "Present" at an Assembly or other meeting means to be either personally present at the meeting location or participating via teleconferencing mechanisms. Especially, this means that members can also vote if present via teleconferencing.

Current Swedish law only allows for 
- in-presence assemblies _at one specified in Sweden specified in the bylaws_ (e.g. Linköping)
- digital assemblies

So, for convenience we should only leave a provision for digital assemblies.

Of course, nothing prevents some people to gather at a specific place anywhere on Earth from which to connect to the digital assembly from the same room, but this needs not be stated in the bylaws.

**Comment by HansOlsson** [comment]
Covered in https://github.com/modelica/MA-Bylaws/pull/28/commits/35159c0f38ad99aa0440160cee497154503bd0d5 (well, part undone in https://github.com/modelica/MA-Bylaws/pull/28/commits/7e15a6869d7926206d51020e63c7e027b7e664a3 )
