### ISSUE TITLE
Update provisions for dates of assembly meetings 

### ISSUE THREAD

**Issue by casella** [modelica/MA-Bylaws#24]
The current Section 12 of the bylaws states:
> The Assembly determines dates for Assembly meetings during the year. When necessary, the Board can schedule additional Assembly meetings. At least two Assembly meetings per year have to take place, one of them is the Annual Assembly meeting. On written request by a member of the Board, or accountant or members representing at least four votes, the Board must call an additional Assembly meeting.

This is quite awkward when going digital. Proposal: the Board sets the dates of the Assemblies.

> For Assembly meetings, the Chairperson must send notice of the meeting including date, location and preliminary agenda to MA members in writing or via email at least five weeks before the meeting.

Five weeks is probably too long for digital meetings. Swedish laws by default says four to six weeks, but allow to reduce it to two. 

Proposal: at least two weeks before (but not more than six, which would be illegal)

Christian, Francesco, Hanse, Pierre: OK

Christian, Francesco, Hans, Pierre: OK

**Comment by chrbertsch** [comment]
Lets keep the 5 weeks announcement time, to accomodate time planning and proposals for the agenda.
