### ISSUE TITLE
Bylaw changes due to law

### ISSUE THREAD

**Issue by HansOlsson** [modelica/MA-Bylaws#27]
(Based on a previous e-mail; I hope I haven't missed anything - but feel free to check). I checked the Swedish law and there are some minor issues that should be changed/added:

- [x] Minimum and maximum number of: board members, accountants, and alternate members (if any). https://github.com/modelica/MA-Bylaws/pull/28/commits/3cb33874507d516067c77a3bf65fe02587b1ccd6
- [x] And how long they are elected for (note that the current bylaws state that elections are held every other year; that’s not necessarily the same as many organizations have elections annually but still elect people for two years to ensure continuity (with overlapping terms) – maximum four years); https://github.com/modelica/MA-Bylaws/pull/28/commits/77c05aa06aa92033f6a35ada26af4a2682c6001e
- [x] How to use the profits (if any); even if the “non-profit” part should make that clear; 27ec634eea261dc9b0420a3717f7d635c4d178a9
- [x] How the remaining funds will be distributed in case the association is dissolved; d1edac45c4cb3558b6d652105a1fcfec57f7c073
- [x] (Maximum) annual fees shall be listed; d125f3b155bcf32d103b2ead304c32215664f9db
- [x] The by-laws should state that the annual meeting is held digitally (if nothing is specified it has to be at the city where it is located, Linköping; the by-laws could also specify another city in Sweden); only one meeting per year is needed; #23
- [x] A minor note: the qualified majority needed for changing the by-laws should be two-thirds, not >66%; https://github.com/modelica/MA-Bylaws/pull/28/commits/09737e3f9b4e6675d8c3a7ddd753dc37c554cab7

We could also change:
- How long before the meeting the invite to the annual meeting is sent; default is 4-6 weeks, but the by-laws can lower it to 2 weeks; https://github.com/modelica/MA-Bylaws/pull/28/commits/c9e1d3ce95577a687525927dc29a0222137fd563
- [x] The default is that the board (not the general assembly as in our by-laws) approves new applicants, but the by-laws takes precedence; #22
- Whether the accounting is in Euro (and in that case some fees must be in Euro – I don’t see that the reverse is true).

And various things that don't have to be in the by-laws, but are still important:
-  The boards needs to have a register of members, with name and postal address (Sweden is not yet fully digital) – and date when joined. All members are allowed to see it; and old members kept for seven years.
- Especially for non-swedes the following is quite important:
  - At least half of the board must reside within the European Economic Area
  - If we want a CEO (separate from the chair) they must reside within the European Economic Area
  - At least one signing authority must reside in the European Economic Area

Reference: 
https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/lag-2018672-om-ekonomiska-foreningar_sfs-2018-672/

**Comment by chrbertsch** [comment]
Hans, Francesco, Christian: 

- How to use the profits (if any); even if the “non-profit” part should make that clear.
Francesco: Use them to achieve the purposes of MA.
Hans: It should enough, that profits should be carried forward to the next years budget.
- How the remaining funds will be distributed in case the association is dissolved
Christian: Donate them to some other non-profit organization that follow similar goals as MA?
- (Maximum) annual fees shall be listed.
Francesco: 20.000 for organization members  (to have some stability for the next time)
