### ISSUE TITLE
Compliance and Antitrust Statement of MA

### ISSUE THREAD

**Issue by chrbertsch** [modelica/MA-Bylaws#6]
Companies today expect organizations as MA to have a Compliance and Antitrust statement
Example ISO: https://www.iso.org/files/live/sites/isoorg/files/developing_standards/docs/en/competition_law_guidelines.pdf

As proposed by the FMI Steering committee and agreed with @MartinOtter , we will use a branch of this repo to work on a proposal.
It is not intended to propose Bylaw changes; it will be  sufficient to have a vote by the MA Assembly to accept a proposed text.

I started with https://github.com/modelica/MA-Bylaws/tree/ComplianceAndAntiTrustStatement in a branch, feel free to comment and improve the text.

@hubertus65 and @chrbertsch will work on the proposal; anyone is free to contribute.

**Comment by MartinOtter** [comment]
The sentence:

> The Guidelines address all meetings and exchange of information within the MA standards development process and are addressed to all participants such as delegates, chairs and secretaries of TCs and SCs as well as experts and conveners in WGs. 

needs to be changed (I guess TCs and SCs are from ISO). Maybe:

- The Guidelines address all meetings and exchange of information within the MA standards development process and are in particular addressed to all participants and visitors of MA meetings.

Maybe the following sentences should be removed:

> Compliance with competition law in the standard setting process is essential to ensure
> i) that markets oper-ate efficiently and competitively; and
> ii) that the ISOstandards development process remains a platform of trust for industries.
 
> Do follow MA rules and procedures ???, including those many policies that concern compliance with competition law, such as the ISO Code of Conduct.???
> ???Do follow the ISO-IEC-ITU Common Patent Policy and Guidelines.???

Change
>  ???ISO’s legal team???, as soon as possible afterwards.

to
- the MA board as soon as possible afterwards.

**Comment by chrbertsch** [comment]
@MartinOtter :  I updated the proposal according to your suggestions, please check
https://github.com/modelica/MA-Bylaws/commit/8a37881f5a74ddc29ba60f2011ba69c04e6e11aa
(You are also very welcome to commit directly to this branch)
